### ISSUE TITLE
Built in Windows emoji picker

### ISSUE THREAD

**Issue by mikeseese** [swharden/Tmoji#1]
I was looking for something like this just 2 days ago!

Love the idea, and definitely keep building if you want! I just wanted to let you know if you didn't already, Windows has a built in tool for this by using the key combo `Win+.` https://www.howtogeek.com/351344/how-to-use-windows-10%E2%80%99s-new-emoji-picker-in-any-app/

Hope all is well!

**Comment by swharden** [comment]
Hey @seesemichaelj it's great to hear from you! 

I frequently go to write things like `λ (± 1 nm)` and `123 MΩ` in text documents and scientific applications and I forget the alt-codes (e.g., ALT+234) so I made Tmoji last night to make that easier. I branded it with emoji because I figured that would be a more common/relatable use case.

... but I hadn't heard of `Win` + `.` until you mentioned it, and it looks like this built-in Windows 10 application nails it! It might be time to shut down this repo 😝 "A few days of programming can save you hours on Google"

**Comment by mikeseese** [comment]
🤯 I DID NOT SEE IT DID SYMBOLS TOO!

> A few days of programming can save you hours on Google"

😂

**Comment by swharden** [comment]
I spent a couple days working with `Win` + `.` and it's close to meeting my needs, but I still personally want something faster. I think the main advantage of Tmoji is its speed (2 clicks), so perhaps the project would benefit from better branding to highlight this point.

Consider this: to insert a plusminus sign (`±`) you have to hit `Win` + `.`, click the `Ω`, then figure out what category that thing is under (it's under `<` by the way, not in `∞` which contains `∓`). Come to think of it, where is the `∞` anyway? It's not in the `∞` category! Bottom line is that to insert a `±` I need to do a lot of hunting. Even if I get it in my recent history, it still requires to press two keys then click 3 times to get there. I've been using the windows tool a lot since learning about it from you and it's nice to have, but I think there's still room for something faster. With Tmoji, one click of the icon opens a customized list of emojis/symbols, then just 1 click copies the one you want. 

I think Tmoji's increased speed and simpler customization (displayed emoji/symbols are loaded from a configuration a text file) means I'll personally keep using it over the windows tool. For me it seems worthwhile to put a little more time into developing/refining it, and we'll see where it goes from there.

![image](https://user-images.githubusercontent.com/4165489/102559743-985a5780-409e-11eb-90d3-6e3398782424.png)

**Comment by mikeseese** [comment]
Ya the symbols picker does not have a good (or existing? lol) search/filter interface. With the emojis, you can just type "smile" after `Win + .` and it will filter the emojis. However typing "lambda" after clicking on the symbols tab does not work. So with that, I totally see your interface being better/easier for symbols, but definitely not for emojis since you can type it right away

FWIW, I did find `∞` under the `∞` category, but it's near impossible to sift through it all without a working filter for "infinity"

**Comment by swharden** [comment]
Hey @seesemichaelj! Following-up on this, after using Tmoji for a couple months I found it super useful over Windows' built-in picker. It's way faster to get to the emoji/symbols you need (which you typically can plan for in advance), and I found myself using it a lot during screen-sharing Zoom meetings to add special characters to text documents (mostly ✔️❌❓⚠️± and ↑↓). When typing a sentence or formula, a brief Tmoji pop-up in the corner is a lot faster than the center-screen multi-page windows picker.

So, fundamentally the windows picker does the same thing, but Tmoji's slight speed advantage makes it worth using for me personally. When you first commented above I thought about pulling the plug on Tmoji, but now I think it probably merits being its own application. I've certainly found it useful!

Thanks again for pointing out the `Win + .` method. I added a note of it to the emoji editor screen as one way users can add different emoji and symbols when editing the list.

**Comment by mikeseese** [comment]
Totally fair! Unfortunately, I'm on a 4 monitor setup so a system tray activation is not ideal for me. `Win + .` however does not work at all for symbols since it doesn't have a quick search, but for emojis, I can insert an emoji without ever having to touch the mouse. 🤷

Glad you got something that works for you! I'll just wait for Windows to make their symbols searchable haha

**Comment by swharden** [comment]
4 monitors - nice! For mouse-free emojis in VS code, [emojisense](https://marketplace.visualstudio.com/items?itemName=bierner.emojisense) looks pretty good

**Comment by mikeseese** [comment]
emojisense ise great! I use it in my commits and comments frequently; highly recommend
